docs/source/index.rst, docs/source/rules/go/index.rst, docs/source/rules/go/stdlib/crypto_weak_cipher.rst, docs/source/rules/go/stdlib/crypto_weak_hash.rst, docs/source/rules/go/stdlib/crypto_weak_key.rst, docs/source/rules/go/stdlib/index.rst, docs/source/rules/python/stdlib/assert.rst, docs/source/rules/python/stdlib/crypt_weak_hash.rst, docs/source/rules/python/stdlib/ftplib_cleartext.rst, docs/source/rules/python/stdlib/hashlib_weak_hash.rst, docs/source/rules/python/stdlib/hmac_timing_attack.rst, docs/source/rules/python/stdlib/hmac_weak_hash.rst, docs/source/rules/python/stdlib/imaplib_cleartext.rst, docs/source/rules/python/stdlib/json_load.rst, docs/source/rules/python/stdlib/logging_insecure_listen_config.rst, docs/source/rules/python/stdlib/marshal_load.rst, docs/source/rules/python/stdlib/nntplib_cleartext.rst, docs/source/rules/python/stdlib/pickle_load.rst, docs/source/rules/python/stdlib/poplib_cleartext.rst, docs/source/rules/python/stdlib/shelve_open.rst, docs/source/rules/python/stdlib/smtplib_cleartext.rst, docs/source/rules/python/stdlib/ssl_context_weak_key.rst, docs/source/rules/python/stdlib/ssl_create_unverified_context.rst, docs/source/rules/python/stdlib/ssl_insecure_tls_version.rst, docs/source/rules/python/stdlib/telnetlib_cleartext.rst, docs/source/rules/python/stdlib/tempfile_mktemp_race_condition.rst
Change the title of each doc to match the name of the rule. Also added missing docs.
=> Fix links and titles to docs

docs/source/man/precli.rst
* Ensure the arguments match current function
* Add info on .preignore file
* Better description
=> Update man page to reflect current function

.github/workflows/dependency-review.yml
Ensure dependencies with vulnerabilities aren't introduced.
=> Add a dependency review workflow action

.github/workflows/dependency-review.yml
Update to checkout v4 and dependency-review-action v4.
=> Bump versions of actions used

.github/workflows/dependency-review.yml
Deny licenses that are GPL based.
=> Prohibit GPL based licenses being introduced

docs/source/man/precli.rst
Expand the man page to include guidelines on how to report a bug.
=> Add a Reporting Bugs section

precli/renderers/__init__.py, precli/renderers/detailed.py, precli/renderers/json.py, precli/renderers/plain.py
Just pass the run instead of the members of the run.
=> Refactor arguments to renderers

precli/cli/main.py, precli/core/result.py
Append "#L<line num>-L<line num>" to the URIs of results.
NOTE: this would apply to GitHub only. Future source control might not.
=> Add line numbers in the URI

precli/parsers/python.py, precli/rules/python/stdlib/http_url_secret.py, tests/unit/rules/python/stdlib/examples/http_url_secret_basic_auth.py, tests/unit/rules/python/stdlib/examples/http_url_secret_basic_auth_as_var.py, tests/unit/rules/python/stdlib/test_http_url_secret.py
* Check for basic auth authentication in a URL
* Check for cases where url argument is a varible
=> Add further tests for rule http_url_secret

docs/source/man/precli.rst, precli/cli/main.py, precli/renderers/markdown.py
Outputs in markdown. However, this markdown matches the schema of GitHub. So the output to the console may not be as nicely presented as it would on GitHub.
Closes #290
=> New renderer to output in markdown format

precli/cli/main.py, precli/renderers/__init__.py, precli/renderers/detailed.py, precli/renderers/json.py, precli/renderers/markdown.py, precli/renderers/plain.py
* Use rich file option if given an output file
* Fix up the markdown file output to be rendable in Gist
* Use the no_color option of rich console
=> Fix up the renderer outputs

README.rst
Add more details to getting started in README
=> Add more details to getting started in README

precli/core/symtab.py, precli/parsers/__init__.py, precli/parsers/go.py, precli/parsers/python.py
* Rename Parser's first_match to child_by_type
* Add return types to symbol table methods
* Add an "in" function to symtab
=> Slight refactoring of symtab and base parser

precli/parsers/python.py, precli/rules/python/stdlib/assert.py, tests/unit/rules/python/stdlib/examples/assert.py, tests/unit/rules/python/stdlib/test_assert.py
Finish up the assert rule and add test cases.
=> Finish up the assert rule

precli/renderers/json.py
=> Fix up the output to adhere to SARIF schema

README.rst
* Add mention of Precaution App and Action.
* Add pointer to Precaution Pro for additional functionality
=> Add more details to README

precli/rules/python/stdlib/http_url_secret.py, precli/rules/python/stdlib/imaplib_cleartext.py, precli/rules/python/stdlib/logging_insecure_listen_config.py, precli/rules/python/stdlib/nntplib_cleartext.py, precli/rules/python/stdlib/poplib_cleartext.py, precli/rules/python/stdlib/smtplib_cleartext.py, precli/rules/python/stdlib/ssl_context_weak_key.py
Its easier on the eyes to use entry guards into functions rather than deep nested if-statements.
=> Use guards instead of nested if conditionals

precli/renderers/json.py
Renamed create_rule_if_not_exists to create_rule_if_needed.
=> Rename function to be more clear

docs/rules.md, docs/rules/python/stdlib/re-denial-of-service.md, precli/core/redos.py, precli/rules/python/stdlib/re_denial_of_service.py, setup.cfg, tests/unit/rules/python/stdlib/re/examples/re_compile.py, tests/unit/rules/python/stdlib/re/examples/re_compile_good.py, tests/unit/rules/python/stdlib/re/examples/re_findall.py, tests/unit/rules/python/stdlib/re/examples/re_finditer.py, tests/unit/rules/python/stdlib/re/examples/re_fullmatch.py, tests/unit/rules/python/stdlib/re/examples/re_match.py, tests/unit/rules/python/stdlib/re/examples/re_search.py, tests/unit/rules/python/stdlib/re/examples/re_search_good.py, tests/unit/rules/python/stdlib/re/examples/re_split.py, tests/unit/rules/python/stdlib/re/examples/re_sub.py, tests/unit/rules/python/stdlib/re/examples/re_subn.py, tests/unit/rules/python/stdlib/re/test_re_denial_of_service.py
New rule that checks various functions of the re module for suspicious patterns that might cause catastrophic backtracking.
Closes: #371
=> Add new rule to detect regex denial-of-service patterns

precli/__init__.py
Adds __copyright__ into the module.
=> Embed the copyright as part of the package

precli/parsers/python.py
The node type of "string" can be a byte string in addition to a regular string.
=> Add ability to process a byte string value

precli/parsers/java.py
This adds interface, annotation type, enum, record declarations.
=> Add more symbol tables for other declarations

precli/parsers/python.py
This change adds the child_by_type() function to the tree-sitter Node class as a convenience function.
Note: this is only added to Python parser for now as other languages might support child_by_field_name(). tree-sitter-python apparently does not support child_by_field_name.
=> Enhance the Node class with convenient functions

precli/parsers/__init__.py, precli/parsers/go.py, precli/parsers/java.py, precli/parsers/python.py
The new property added to Node returns the text decoded in UTF-8.
=> Add Node convenient function utf8_text

.github/workflows/upload-asset.yml
https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
=> Add attestation to build artifacts

precli/renderers/json.py
Additional rules are loaded via the importlib's entry_points.
This change uses the distribution metadata for any extension
that starts with "precli-" for the SARIF output.
=> Load metadata for any extension entry points

precli/core/run.py
This change moves some of the processing from invoke into the parser_file method which makes more logical sense.
=> Refactor the invoke function in the run class

precli/cli/main.py, precli/core/loader.py, precli/core/metrics.py, precli/core/result.py, precli/core/run.py, precli/parsers/__init__.py, precli/parsers/go.py, precli/parsers/java.py, precli/parsers/python.py, precli/renderers/detailed.py, precli/renderers/json.py, precli/renderers/markdown.py, precli/renderers/plain.py, precli/rules/__init__.py, tests/unit/rules/python/stdlib/json/test_json_load.py, tests/unit/rules/test_case.py
Makes use of multiprocessing pool to process each file in a pool rather than processing serially.
This results in significant speed improvements. Scanning cpython went from 34 seconds to just 9-10 seconds.
=> Support multiprocessing of file parsing

precli/core/run.py
The keyboard interrupts should be handled in the main process not in the child worker pool processes.
=> Redo handling of keyboard interrupts

precli/renderers/detailed.py, precli/renderers/json.py, precli/renderers/markdown.py, precli/renderers/plain.py
=> Fix for traceback in plain renderer

precli/cli/main.py, precli/core/run.py
Move the Tool initialization to the Run object.
=> Small refactor on where Tool is initialized

precli/core/run.py
The Rich Progress class supports a column to print out the number of completed vs total number. This change adds the new column which effectively shows the number of files analyzed vs total number of files targeted.
=> Add number of complete count to progress

precli/cli/main.py, precli/core/redos.py, precli/parsers/go.py, precli/parsers/python.py, precli/renderers/detailed.py, precli/renderers/json.py, precli/renderers/markdown.py, precli/renderers/plain.py, precli/rules/python/stdlib/ftplib_cleartext.py, precli/rules/python/stdlib/hashlib_improper_prng.py, precli/rules/python/stdlib/hashlib_weak_hash.py, precli/rules/python/stdlib/json_load.py, precli/rules/python/stdlib/marshal_load.py, precli/rules/python/stdlib/ssl_insecure_tls_version.py, precli/rules/python/stdlib/tempfile_mktemp_race_condition.py, pylintrc
Clean up most of the warnings from pylint and flake8.
=> Fix up warnings from pylint and flake8

precli/core/cwe.py
Add 215 and description to the Cwe class as a possible vulnerability.
=> Add CWE 215 as possible code

.github/workflows/unit-test.yml, setup.cfg
Adds official Windows support as a result of unit testing on Windows as part of the CI/CD.
=> Add Windows support and unit testing

precli/core/artifact.py
Some of the setter functions were missing types on the args. Also, to be consistent, switched to using Optional instead of <type> | None.
=> Set types on args of setters

precli/core/argument.py, precli/core/config.py, precli/core/run.py, precli/core/symtab.py
* Make sure more function args have types
* Use Optional where imported for consistency
* If an optional type, check if not None
=> More type fixes

README.rst
The repobeats website provides a nice generator of SVG images to show repository stats and activity.
https://repobeats.axiom.co/
=> Add repo activity to README

README.rst
Add links to the Precaution GitHub App and Action
=> Add links to App and Action

precli/core/cwe.py
* Use a dict for the ID to name mapping rather than many return statements.
=> Refactor Cwe class to be more pythonic

docs/getting-started.md, docs/index.md, docs/rules.md
For some of the higher level doc pages, it is nice to have a last updated text at the bottom of the page so readers know when it was last changed.
=> Add last updated date on doc pages

README.rst
Adds:
* docs status
* latest version on PyPI
* supported python versions
* PyPI format
* monthly downloads
=> Add some more badges to the README

setup.cfg
Some change to ensure this program is Python 3 only.
=> Update classifier to specify Python 3 only

precli/rules/go/stdlib/crypto_weak_key.py, precli/rules/java/stdlib/java_security_weak_key.py, precli/rules/python/stdlib/ssl_context_weak_key.py
Small change to rename the key size configuration variables.
=> Rename of the key size config variables

precli/cli/main.py
This code allows someone to pass argument -c, --config to pass a customized configuration file. It also checks for .precli.toml, precli.toml, and pyproject.toml files that may exist in a directory given by targets.
=> New CLI argument to accept a custom configuration file

precli/cli/main.py
Pass need parameters instead of the argparse args object.
=> Small change to parameters of load_config

docs/man/precli.md
The man page is missing information on the new --config argument.
=> Fix outdated man page

precli/cli/main.py, tests/unit/cli/test_main.py
The unit testing was lacking any testing at all. This change adds coverage of CLI loading of configuration files.
=> Add some testing of CLI loading of config

precli/cli/main.py, precli/renderers/__init__.py, precli/renderers/detailed.py, precli/renderers/plain.py
The quiet argument wasn't being handled in any way. This change handles quiet mode in the detailed and plain renderer to not display any summary information in the output.
=> Properly handle quiet mode

precli/cli/main.py
This change simplifies the loading of the targets.
=> Small refactor in the loading of targets extension

tests/unit/cli/test_init.py, tests/unit/cli/test_main.py
* Some unnecessary mocking removed
* Removal of setup and teardown which was unneeded
=> Clean up and refactor CLI unit tests

precli/i18n.py, precli/locale/de/LC_MESSAGES/messages.po, precli/locale/en_GB/LC_MESSAGES/messages.po, precli/locale/es/LC_MESSAGES/messages.po, precli/locale/fr/LC_MESSAGES/messages.po, precli/locale/it/LC_MESSAGES/messages.po, precli/locale/ja/LC_MESSAGES/messages.po, precli/locale/ko/LC_MESSAGES/messages.po, precli/locale/pt_BR/LC_MESSAGES/messages.po, precli/locale/ru/LC_MESSAGES/messages.po, precli/locale/zh_CN/LC_MESSAGES/messages.po, precli/locale/zh_TW/LC_MESSAGES/messages.po, tox.ini
This change translates each message. The lookup code was also modified and tested to properly find the message based on the detect system locale.
=> Translate message files and enable correct lookup

precli/cli/init.py, precli/cli/main.py, precli/core/cwe.py, precli/renderers/detailed.py, precli/renderers/plain.py, tox.ini
This new msgfmt step of tox will compile the *.po files into *.mo binaries suitable to be loaded for specific locale.
This change also add additional strings available to translate.
=> Add msgfmt step to tox

.pre-commit-config.yaml
Updates to the latest versions and uses mirrors if available.
=> Update the pre-commit config versions

setup.cfg
Adds each language the CLI is translated for.
=> Add setupttools classifiers for translated languages

mkdocs.yml
=> Update copyright year in docs

precli/rules/go/stdlib/crypto_weak_key.py, precli/rules/java/stdlib/java_security_weak_key.py, precli/rules/java/stdlib/javax_crypto_weak_cipher.py, precli/rules/java/stdlib/javax_servlet_http_insecure_cookie.py, precli/rules/python/stdlib/ftplib_cleartext.py, precli/rules/python/stdlib/ftplib_no_timeout.py, precli/rules/python/stdlib/hashlib_weak_hash.py, precli/rules/python/stdlib/imaplib_cleartext.py, precli/rules/python/stdlib/imaplib_unverified_context.py, precli/rules/python/stdlib/json_load.py, precli/rules/python/stdlib/logging_insecure_listen_config.py, precli/rules/python/stdlib/marshal_load.py, precli/rules/python/stdlib/nntplib_cleartext.py, precli/rules/python/stdlib/nntplib_unverified_context.py, precli/rules/python/stdlib/pickle_load.py, precli/rules/python/stdlib/poplib_cleartext.py, precli/rules/python/stdlib/poplib_unverified_context.py, precli/rules/python/stdlib/secrets_weak_token.py, precli/rules/python/stdlib/shelve_open.py, precli/rules/python/stdlib/smtplib_cleartext.py, precli/rules/python/stdlib/smtplib_unverified_context.py, precli/rules/python/stdlib/ssl_context_weak_key.py, precli/rules/python/stdlib/ssl_create_unverified_context.py, precli/rules/python/stdlib/ssl_insecure_tls_version.py
* Some strings had extra quotes in them
* Some string line lengths could be extended
=> Redo translated strings

.github/workflows/unit-test.yml
Ensure unit tests are running on both push and created PRs.
This also removes the ignore of the README which had issues.
=> Run unit tests on push and PR
