precli/cli/main.py

Conform to command line standards when the DEBUG environment variable is set.
https://clig.dev/#environment-variables

Represent env var DEBUG if set

---

.github/workflows/unit-test.yml

Only run unit tests on the creation of a pull requests and not also a push event.

Only trigger unit tests on pull requests

---

.github/workflows/publish-to-pypi.yml
.github/workflows/publish-to-test-pypi.yml

PyPI recently introduced trusted publishing from sources such as GitHub Actions. This change takes advantage of that for publishing to PyPI and Test PyPI.
https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/

Add trusted publishing to PyPI

---

.github/workflows/publish-to-test-pypi.yml
setup.cfg

PyPI doesn't support direct dependencies so we can't use it as an extra.

Remove reference to direct dependencies

---

.github/workflows/unit-test.yml
setup.cfg

* Unit tests will now run on macOS.
* The PyPI classifier updated to declare macOS

Add support and testing of macOS

---

precli/cli/main.py

The is_ignored() function expects paths relative to the starting path given when initializing the class. It raises a traceback if given an absolute path.
```
Traceback (most recent call last):
File "/Users/ericwb/workspace/precli/.tox/py312/bin/precli", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/ericwb/workspace/precli/precli/cli/main.py", line 301, in main
file_list = discover_files(args.targets, args.recursive)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ericwb/workspace/precli/precli/cli/main.py", line 177, in discover_files
if not preignore_mgr.is_ignored(path):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ericwb/workspace/precli/.tox/py312/lib/python3.12/site-packages/ignorelib.py", line 401, in is_ignored
matches = list(self._find_matching(path)) …
```

Only use relative paths with function is_ignored()

---

precli/cli/main.py
precli/core/linecache.py
precli/core/loader.py
precli/core/location.py
precli/core/result.py
precli/parsers/__init__.py
precli/parsers/go.py
precli/parsers/java.py
precli/parsers/python.py
precli/renderers/detailed.py
precli/renderers/json.py
precli/renderers/plain.py
requirements.txt

* If the argument "-" is passed, that tells precli to read the file from stdin.
* Use the existing dependency of rich and Pygments to guess the lexer since there is no file name in this case.
* This change also gets rid of the file extension logic of the parsers and just keeps a lexer name instead.
Closes #214

Support passing a file via standard input

---

precli/__init__.py
precli/cli/main.py
precli/core/artifact.py
precli/core/run.py
precli/core/tool.py
precli/parsers/__init__.py
tests/unit/parsers/test_go.py
tests/unit/parsers/test_python.py
tests/unit/rules/python/stdlib/test_ftplib_cleartext.py
tests/unit/rules/test_case.py

New class objects closely matching SARIF.
* New Tool class to represent information about precli itself
* New Run class to represent an instance of a run of the analysis
* New Artifact class representing the files, source language, and contents.

Refactor into run, tool, artifacts

---

precli/core/location.py
precli/core/result.py
precli/parsers/__init__.py
precli/renderers/detailed.py
precli/renderers/json.py
precli/renderers/plain.py
precli/rules/go/stdlib/crypto_weak_cipher.py
precli/rules/go/stdlib/crypto_weak_hash.py
precli/rules/go/stdlib/crypto_weak_key.py
precli/rules/python/stdlib/assert.py
precli/rules/python/stdlib/crypt_weak_hash.py
precli/rules/python/stdlib/ftplib_cleartext.py
precli/rules/python/stdlib/hashlib_weak_hash.py
precli/rules/python/stdlib/hmac_timing_attack.py
precli/rules/python/stdlib/hmac_weak_hash.py
precli/rules/python/stdlib/imaplib_cleartext.py
precli/rules/python/stdlib/json_load.py
precli/rules/python/stdlib/logging_insecure_listen_config.py
precli/rules/python/stdlib/marshal_load.py
precli/rules/python/stdlib/nntplib_cleartext.py
precli/rules/python/stdlib/pickle_load.py
precli/rules/python/stdlib/poplib_cleartext.py
precli/rules/python/stdlib/shelve_open.py
precli/rules/python/stdlib/smtplib_cleartext.py
precli/rules/python/stdlib/ssl_context_weak_key.py
precli/rules/python/stdlib/ssl_create_unverified_context.py
precli/rules/python/stdlib/ssl_insecure_tls_version.py
precli/rules/python/stdlib/telnetlib_cleartext.py
precli/rules/python/stdlib/tempfile_mktemp_race_condition.py

* Pass the artifact to the location instead of just file name
* Load the snippet with the initialization of the location

Use artifact in context

---

precli/core/result.py
precli/parsers/__init__.py
precli/rules/go/stdlib/crypto_weak_cipher.py
precli/rules/go/stdlib/crypto_weak_hash.py
precli/rules/go/stdlib/crypto_weak_key.py
precli/rules/python/stdlib/crypt_weak_hash.py
precli/rules/python/stdlib/ftplib_cleartext.py
precli/rules/python/stdlib/hashlib_weak_hash.py
precli/rules/python/stdlib/hmac_timing_attack.py
precli/rules/python/stdlib/hmac_weak_hash.py
precli/rules/python/stdlib/imaplib_cleartext.py
precli/rules/python/stdlib/json_load.py
precli/rules/python/stdlib/logging_insecure_listen_config.py
precli/rules/python/stdlib/marshal_load.py
precli/rules/python/stdlib/nntplib_cleartext.py
precli/rules/python/stdlib/pickle_load.py
precli/rules/python/stdlib/poplib_cleartext.py
precli/rules/python/stdlib/shelve_open.py
precli/rules/python/stdlib/smtplib_cleartext.py
precli/rules/python/stdlib/ssl_context_weak_key.py
precli/rules/python/stdlib/ssl_create_unverified_context.py
precli/rules/python/stdlib/ssl_insecure_tls_version.py
precli/rules/python/stdlib/telnetlib_cleartext.py
precli/rules/python/stdlib/tempfile_mktemp_race_condition.py

In order to simplify the rules, this change reduces the need to pass the file artifact when initializing the Result. This amounts to less code in each Rule. The artifact still gets set, but later in the parser. As a result, the snippet and artifact URI are also set later.

Make the artifact argument of a Result to be lazy set

---

precli/parsers/__init__.py

Recent change to remove the artifact from the context causes a traceback when visiting an ERROR node which needs the file name.
Fixes: #272

Fix traceback on syntax errors

---

precli/cli/main.py
precli/core/run.py

This is to prevent the unintential log messages from urllib3 via requests appearing as stdout.
Fixes: #275

Set logging level on urllib

---

precli/core/result.py
precli/renderers/detailed.py

This change moves the line suffix of the URI back over to the detailed renderer instead of in the Result object.
Fixes: #278

Fix for bad artifact URI

---

precli/core/run.py
precli/parsers/__init__.py
precli/parsers/go.py
precli/parsers/java.py
precli/parsers/python.py

Relying on rich Syntax to guess the lexer in all cases is problemmatic. It would actually hang on some files.
Therefore, reverting to using file extensions to identify the lexer type as the primary method. Only use pygments guess_lexer when the file is standard input.

Better languages detection

---

docs/source/man/precli.rst

Further information in the man page about details on any environment variables that precli will read.
Currently the only read variable is DEBUG. When any value is set, it will turn on debug logging.

Add environment variables section to man page

---

precli/rules/python/stdlib/http_url_secret.py
setup.cfg
tests/unit/rules/python/stdlib/examples/http_url_secret_apikey.py
tests/unit/rules/python/stdlib/examples/ssl_context_set_ecdh_curve_unverified_context.py
tests/unit/rules/python/stdlib/test_http_url_secret.py
tests/unit/rules/python/stdlib/test_imaplib_cleartext.py
tests/unit/rules/python/stdlib/test_json_load.py
tests/unit/rules/python/stdlib/test_logging_insecure_listen_config.py
tests/unit/rules/python/stdlib/test_marshal_load.py
tests/unit/rules/python/stdlib/test_nntplib_cleartext.py
tests/unit/rules/python/stdlib/test_pickle_load.py
tests/unit/rules/python/stdlib/test_poplib_cleartext.py
tests/unit/rules/python/stdlib/test_smtplib_cleartext.py
tests/unit/rules/python/stdlib/test_ssl_context_tls_version.py
tests/unit/rules/python/stdlib/test_ssl_context_weak_key.py
tests/unit/rules/python/stdlib/test_ssl_create_context.py
tests/unit/rules/python/stdlib/test_ssl_get_server_certificate_tls_version.py
tests/unit/rules/python/stdlib/test_ssl_wrap_socket_tls_version.py
tests/unit/rules/python/stdlib/test_telnetlib_cleartext.py
tests/unit/rules/python/stdlib/test_tempfile_mktemp_race_condition.py

Checks for sensitive parameters in a URL such as apiKey, password, or username passed into a HTTPConnection or HTTPSConnection request function.
Closes #218

New rule for secrets in HTTP URL parameters

---

tests/unit/rules/python/stdlib/examples/http_url_secret_apikey_in_header.py
tests/unit/rules/python/stdlib/examples/http_url_secret_password.py
tests/unit/rules/python/stdlib/examples/http_url_secret_username.py
tests/unit/rules/python/stdlib/test_http_url_secret.py

Add tests of apikey, password, and username in the URL. Also add a compliant case where the apikey is in the header.

Add more testing of HttpUrlSecret rule

---

precli/renderers/json.py
requirements.txt

* Repurposes the json renderer to use the SARIF schema
* Adds couple new dependencies on:
- sarif-om - SARIF library created by Microsoft
- jschema-to-python - library to convert SARIF schema to json
https://github.com/microsoft/sarif-python-om
https://github.com/microsoft/bandit-sarif-formatter
Closes #224

Use SARIF schema for JSON output

---

precli/renderers/detailed.py
precli/renderers/json.py
precli/renderers/markdown.py
precli/renderers/plain.py

Printing output to a captured console will help later when there is an option to send the output to a file instead of the console.

Use rich console capture of printed text

---

docs/source/man/precli.rst
precli/cli/main.py
precli/renderers/__init__.py
precli/renderers/detailed.py
precli/renderers/json.py
precli/renderers/markdown.py
precli/renderers/plain.py

Give the user a option to output to a file instead of just stdout. This also disables the color option to the rich console when sent to a file.
Closes #293

Add an output to a file CLI argument

---

docs/source/man/precli.rst
precli/cli/main.py
precli/renderers/markdown.py

* New CLI argument --gist, --output is ignored if using gist
* Create a temporary file to store results of analysis
* After complete, upload results to https://gist.github.com/
* Inform the user of the URL of the Gist created
Note: requires GITHUB_TOKEN environment variable to be set to a valid token of the user in order to upload to Gist.
Closes #296

Add option to output the results to Gist

---

precli/core/run.py

Only set the artifact language if the parser is not None. In other words, only set the value if a parser is found for a supported file extension (just *.py and *.go right now).
Fixes #298

Fix traceback on unsupported files

---

precli/parsers/python.py
tests/unit/rules/python/stdlib/examples/ftp_context_mgr.py
tests/unit/rules/python/stdlib/test_ftplib_cleartext.py

A with context manager doesn't require an as-statement to assign a variable to the call of the context manager.
Fixes #301

Fix traceback when parsing with without as

---

precli/rules/python/stdlib/json_load.py
tests/unit/rules/python/stdlib/test_json_load.py

The json_load rule is far too noisy. As a result,
this change will disable it by default so there isn't a flurry of false positives by default.
It really needs taint analysis instead of the current rule logic.

Change json_load rule to be default of disabled

---

precli/parsers/python.py

If the code being parsed is using type hinting, we can identify the type of a function parameter. As such, we can add that identifier and type to our symbol table to help in detecting issues.

Add varibles of function parameters to symtab

---

precli/parsers/python.py
tests/unit/rules/python/stdlib/examples/ssl_context_set_ecdh_curve_typed_default_param.py
tests/unit/rules/python/stdlib/examples/ssl_context_set_ecdh_curve_typed_param.py
tests/unit/rules/python/stdlib/test_ssl_context_weak_key.py

This change utilizes the visitor pattern to process nodes of type typed_parameter and typed_default_parameter instead of manually checking children of the function def. This works because typed parameters are only within function defs.
This commit also adds test cases to ensure this is working.
This change also protects against the traceback found when encountering an unexpected *arg as a function parameter.
Fixes #310

Rework how a typed parameter is handled

---

precli/renderers/json.py

inserted_content should be an object of type ArtifactContent.

inserted_content does does conform to SARIF schema

---

precli/__init__.py
precli/cli/main.py
precli/core/tool.py
precli/renderers/json.py
precli/rules/go/stdlib/crypto_weak_cipher.py
precli/rules/go/stdlib/crypto_weak_hash.py
precli/rules/go/stdlib/crypto_weak_key.py
precli/rules/python/stdlib/crypt_weak_hash.py
precli/rules/python/stdlib/hashlib_weak_hash.py
precli/rules/python/stdlib/hmac_timing_attack.py
precli/rules/python/stdlib/hmac_weak_hash.py
precli/rules/python/stdlib/json_load.py
precli/rules/python/stdlib/logging_insecure_listen_config.py
precli/rules/python/stdlib/marshal_load.py
precli/rules/python/stdlib/pickle_load.py
precli/rules/python/stdlib/shelve_open.py
precli/rules/python/stdlib/ssl_context_weak_key.py
precli/rules/python/stdlib/ssl_create_unverified_context.py
precli/rules/python/stdlib/ssl_insecure_tls_version.py
precli/rules/python/stdlib/telnetlib_cleartext.py
precli/rules/python/stdlib/tempfile_mktemp_race_condition.py
results.sarif
setup.cfg

* Pass more metadata to the tool component (full description, help_uri, message_strings, etc)
* Return rule metadata in the tool component
* Clean up errors from validation
* Use proper GA'd schema
* Adjust start and end column to match expected by schema

More SARIF cleanup

---

precli/core/level.py
precli/renderers/json.py
precli/rules/go/stdlib/crypto_weak_cipher.py
precli/rules/go/stdlib/crypto_weak_hash.py
precli/rules/python/stdlib/hashlib_weak_hash.py
precli/rules/python/stdlib/hmac_timing_attack.py
precli/rules/python/stdlib/hmac_weak_hash.py
precli/rules/python/stdlib/http_url_secret.py
precli/rules/python/stdlib/imaplib_cleartext.py
precli/rules/python/stdlib/nntplib_cleartext.py
precli/rules/python/stdlib/poplib_cleartext.py
precli/rules/python/stdlib/smtplib_cleartext.py
precli/rules/python/stdlib/ssl_insecure_tls_version.py
precli/rules/python/stdlib/telnetlib_cleartext.py
tests/unit/rules/go/stdlib/test_crypto_weak_cipher.py
tests/unit/rules/go/stdlib/test_crypto_weak_hash.py
tests/unit/rules/python/stdlib/test_hashlib_weak_hash.py
tests/unit/rules/python/stdlib/test_hmac_timing_attack.py
tests/unit/rules/python/stdlib/test_hmac_weak_hash.py
tests/unit/rules/python/stdlib/test_http_url_secret.py
tests/unit/rules/python/stdlib/test_imaplib_cleartext.py
tests/unit/rules/python/stdlib/test_nntplib_cleartext.py
tests/unit/rules/python/stdlib/test_poplib_cleartext.py
tests/unit/rules/python/stdlib/test_smtplib_cleartext.py
tests/unit/rules/python/stdlib/test_ssl_context_tls_version.py
tests/unit/rules/python/stdlib/test_ssl_get_server_certificate_tls_version.py
tests/unit/rules/python/stdlib/test_ssl_wrap_socket_tls_version.py
tests/unit/rules/python/stdlib/test_telnetlib_cleartext.py

In order for GitHub to render a High, Medium, Low for results it requires the security-severity to be set.
This also means each rule needs a default level specific to it to be set. Before it was defaulting to warning, but now will default to the minimum possible value of level in results.

Add security-severity property to sarif rules

---

precli/renderers/json.py
precli/rules/__init__.py

Now that the docstrings are in markdown format, we can safely add them as rule descriptions to the SARIF output so we get better contextual information on a result.

Add rule descriptions to SARIF output

---

precli/renderers/json.py

It seems that GitHub might use the help property instead of long description.

Add help text and markdown for rule

---

precli/renderers/json.py

This change will only populate the rules structure of the run.tool for rules of results found in the analysis. It won't colate all the rules possible, in order to keep the SARIF output file as small as possible.

Keep SARIF output as minimal as possible

---

.github/workflows/unit-test.yml

If just the README file was changed, don't re-run all the tests as it won't have any effect on them.

Skip build for changes to README

---

docs/rules.md
docs/rules/python/stdlib/ftplib_unverified_context.md
precli/core/call.py
precli/rules/python/stdlib/ftplib_unverified_context.py
setup.cfg
tests/unit/rules/python/stdlib/examples/ftplib_ftp_tls_context_as_var.py
tests/unit/rules/python/stdlib/examples/ftplib_ftp_tls_context_none.py
tests/unit/rules/python/stdlib/examples/ftplib_ftp_tls_context_unset.py
tests/unit/rules/python/stdlib/examples/ftplib_ftp_tls_user_password.py
tests/unit/rules/python/stdlib/test_ftplib_unverified_context.py

If a context of unset or None is passed to FTP_TLS, the implementation will default to creating an unverified context. This means the client connection will not properly verify the server its connecting to.
Closes: #341

Add new rule to check for no context being passed to FTP_TLS

---

docs/rules.md
docs/rules/python/stdlib/imaplib_unverified_context.md
precli/rules/python/stdlib/imaplib_unverified_context.py
setup.cfg
tests/unit/rules/python/stdlib/examples/imaplib_imap4_ssl.py
tests/unit/rules/python/stdlib/examples/imaplib_imap4_ssl_context_as_var.py
tests/unit/rules/python/stdlib/examples/imaplib_imap4_ssl_context_none.py
tests/unit/rules/python/stdlib/examples/imaplib_imap4_ssl_context_unset.py
tests/unit/rules/python/stdlib/examples/imaplib_imap4_starttls_context_as_var.py
tests/unit/rules/python/stdlib/examples/imaplib_imap4_starttls_context_none.py
tests/unit/rules/python/stdlib/examples/imaplib_imap4_starttls_context_unset.py
tests/unit/rules/python/stdlib/test_imaplib_unverified_context.py

If a context of unset or None is passed to IMAP4_SSL, the implementation will default to creating an unverified context. This means the client connection will not properly verify the server its connecting to. The instance method of starttls is also vulnerable.
Closes: #345

Add new rule to check for no context being passed to IMAP4_SSL

---

docs/rules.md
docs/rules/python/stdlib/nntplib_unverified_context.md
precli/rules/python/stdlib/nntplib_unverified_context.py
setup.cfg
tests/unit/rules/python/stdlib/nntplib/examples/nntplib_nntp_ssl.py
tests/unit/rules/python/stdlib/nntplib/examples/nntplib_nntp_ssl_context_as_var.py
tests/unit/rules/python/stdlib/nntplib/examples/nntplib_nntp_ssl_context_none.py
tests/unit/rules/python/stdlib/nntplib/examples/nntplib_nntp_ssl_context_unset.py
tests/unit/rules/python/stdlib/nntplib/examples/nntplib_nntp_starttls_context_as_var.py
tests/unit/rules/python/stdlib/nntplib/examples/nntplib_nntp_starttls_context_none.py
tests/unit/rules/python/stdlib/nntplib/examples/nntplib_nntp_starttls_context_unset.py
tests/unit/rules/python/stdlib/nntplib/test_nntplib_unverified_context.py

If a context of unset or None is passed to NNTP_SSL, the implementation will default to creating an unverified context. This means the client connection will not properly verify the server its connecting to. The instance method of starttls is also vulnerable.
Closes: #343

Add new rule to check for context=None in nntp.starttls or NNTP_SSL

---

docs/rules.md
docs/rules/python/stdlib/poplib_unverified_context.md
precli/rules/python/stdlib/poplib_unverified_context.py
setup.cfg
tests/unit/rules/python/stdlib/poplib/examples/poplib_pop3_ssl.py
tests/unit/rules/python/stdlib/poplib/examples/poplib_pop3_ssl_context_as_var.py
tests/unit/rules/python/stdlib/poplib/examples/poplib_pop3_ssl_context_none.py
tests/unit/rules/python/stdlib/poplib/examples/poplib_pop3_ssl_context_unset.py
tests/unit/rules/python/stdlib/poplib/examples/poplib_pop3_stls_context_as_var.py
tests/unit/rules/python/stdlib/poplib/examples/poplib_pop3_stls_context_none.py
tests/unit/rules/python/stdlib/poplib/examples/poplib_pop3_stls_context_unset.py
tests/unit/rules/python/stdlib/poplib/test_poplib_unverified_context.py

If a context of unset or None is passed to POP3_SSL, the implementation will default to creating an unverified context. This means the client connection will not properly verify the server its connecting to. The instance method of stls is also vulnerable.
Closes: #344

Add new rule to check for context=None in stls or POP3_SSL

---

docs/rules.md
docs/rules/python/stdlib/smtplib_unverified_context.md
precli/rules/python/stdlib/nntplib_unverified_context.py
precli/rules/python/stdlib/poplib_unverified_context.py
precli/rules/python/stdlib/smtplib_unverified_context.py
setup.cfg
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_ssl_context_as_var.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_ssl_context_none.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_ssl_context_unset.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_starttls.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_starttls_context_as_var.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_starttls_context_none.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_starttls_context_unset.py
tests/unit/rules/python/stdlib/smtplib/test_smtplib_unverified_context.py

If a context of unset or None is passed to SMTP_SSL, the implementation will default to creating an unverified context. This means the client connection will not properly verify the server its connecting to. The instance method of starttls is also vulnerable.
Closes: #342

Add new rule to check for context=None in smtp.starttls or SMTP_SSL

---

docs/rules.md
docs/rules/python/stdlib/argparse_sensitive_info.md
precli/rules/python/stdlib/argparse_sensitive_info.py
precli/rules/python/stdlib/http_url_secret.py
setup.cfg
tests/unit/rules/python/stdlib/argparse/examples/argparse_add_argument_password.py
tests/unit/rules/python/stdlib/argparse/examples/argparse_add_argument_password_file.py
tests/unit/rules/python/stdlib/argparse/examples/argparse_add_argument_password_store_true.py
tests/unit/rules/python/stdlib/argparse/test_argparse_sensitive_info.py

Sensitive data like a password should not be arguments of a CLI. They would end up appearing in the CLI history, ps output, logs, etc.
Closes: #339

Add rule on argparse to check for an argument of password

---

docs/rules/python/stdlib/secrets_weak_token.md
precli/rules/python/stdlib/secrets_weak_token.py
setup.cfg
tests/unit/rules/python/stdlib/secrets/examples/secrets_token_bytes.py
tests/unit/rules/python/stdlib/secrets/examples/secrets_token_bytes_default.py
tests/unit/rules/python/stdlib/secrets/examples/secrets_token_hex.py
tests/unit/rules/python/stdlib/secrets/examples/secrets_token_urlsafe.py
tests/unit/rules/python/stdlib/secrets/test_secrets_weak_token.py

Tokens should be a sufficient length (32 bytes) to avoid vulnerability of brute-force attacks.

Add new rule for secrets insufficient token length

---

.github/workflows/unit-test.yml
setup.cfg

There is a need to switch from the Python package cwe to cwe2 since cwe2 is more current and maintain better.
However, cwe2 raises an encoding traceback when looking up a CWE in its database.

Drop support of Windows

---

docs/rules.md
docs/rules/python/stdlib/socket-unrestricted-bind.md
precli/parsers/python.py
precli/rules/__init__.py
precli/rules/python/stdlib/socket_unrestricted_bind.py
requirements.txt
setup.cfg
tests/unit/rules/python/stdlib/socket/examples/socket_create_server.py
tests/unit/rules/python/stdlib/socket/examples/socket_socket_bind.py
tests/unit/rules/python/stdlib/socket/examples/socket_socket_bind_as_var.py
tests/unit/rules/python/stdlib/socket/examples/socket_socket_bind_as_vars.py
tests/unit/rules/python/stdlib/socket/test_socket_unrestricted_bind.py

Checks for use of "", "0.0.0.0", or "::" usage when binding sockets.
Partially-fixes: #225

New rule for socket based unrestricted bind

---

docs/rules.md
docs/rules/python/stdlib/socketserver-unrestricted-bind.md
precli/parsers/python.py
precli/rules/python/stdlib/socketserver_unrestricted_bind.py
setup.cfg
tests/unit/rules/python/stdlib/socketserver/examples/socketserver_forking_tcp_server.py
tests/unit/rules/python/stdlib/socketserver/examples/socketserver_forking_udp_server.py
tests/unit/rules/python/stdlib/socketserver/examples/socketserver_tcp_server.py
tests/unit/rules/python/stdlib/socketserver/examples/socketserver_threading_tcp_server.py
tests/unit/rules/python/stdlib/socketserver/examples/socketserver_threading_udp_server.py
tests/unit/rules/python/stdlib/socketserver/examples/socketserver_udp_server.py
tests/unit/rules/python/stdlib/socketserver/test_socketserver_unrestricted_bind.py

Checks for socketserver usage that binds sockets with an unrestricted address such as "", "0.0.0.0", or "::" (IPv6).
Part of #225

Add rule for socketserver unrestricted bind

---

docs/rules.md
docs/rules/python/stdlib/http_server-unrestricted-bind.md
precli/rules/python/stdlib/http_server_unrestricted_bind.py
setup.cfg
tests/unit/rules/python/stdlib/http/examples/http_server_http_server.py
tests/unit/rules/python/stdlib/http/examples/http_server_threading_http_server.py
tests/unit/rules/python/stdlib/http/test_http_server_unrestricted_bind.py

This checks for socket binds in the http.server module that use unrestricted IP addresses ("0.0.0.0" or "::").
Partially implements #225

Add new rule for http.server unrestricted bind

---

docs/rules.md
docs/rules/python/stdlib/xmlrpc-server-unrestricted-bind.md
precli/rules/python/stdlib/xmlrpc_server_unrestricted_bind.py
setup.cfg
tests/unit/rules/python/stdlib/xmlrpc/examples/xmlrpc_server_doc_xml_rpc_server.py
tests/unit/rules/python/stdlib/xmlrpc/examples/xmlrpc_server_simple_xml_rpc_server.py
tests/unit/rules/python/stdlib/xmlrpc/test_xmlrpc_server_unrestricted_bind.py

Checks xmlrpc.server classes that also binds sockets with parameters that allow unrestricted addresses (ANY) as input.
Closes: #225

Add rule for xmlrpc.server unrestricted bind

---

precli/rules/python/stdlib/xmlrpc_server_unrestricted_bind.py

Fix wrong examples in docstring of xmlrpc

---

precli/rules/python/stdlib/argparse_sensitive_info.py
tests/unit/rules/python/stdlib/argparse/examples/argparse_add_argument_api_key.py
tests/unit/rules/python/stdlib/argparse/test_argparse_sensitive_info.py

An api_key is equally as bad as a password argument to a CLI.

Add --api_key checked in the CLI args

---

precli/rules/python/stdlib/argparse_sensitive_info.py
tests/unit/rules/python/stdlib/argparse/examples/argparse_add_argument_api_key.py

Far more common is CLI argument api-key, not api_key.

Check for api-key not api_key

---

.github/workflows/dependency-review.yml
requirements.txt

For build reproducibility, releases should have pinned dependencies.

Pin the dependencies in requirements.txt

---

precli/cli/main.py

During testing, it was found that adding a "tests" to .preignore did not result in the ignoring of that directory in the repo.
It seems the path is needed as input to is_ignored() rather than just file name.
Also noticed that .git files are getting scanned. Normally they should be ignored as part of .gitignore, but its not typical to include there. Seems Git automatically ignores that directory. So I added it as a global_patterns to IgnoreFilterManager. Also figured that it would be good to include global_ignore_file_paths as was in the example for this class to exclude user defined ignores and repo defined ignores.

Fix so preignore properly ignores tests

---

precli/cli/main.py

Previous change was failing when IgnoreFilterManager was given an absolute path (such as when running precli against a GitHub address).
This change uses the computed path only if it's not absolute.

IgnoreFilterManager always requires relative path

---

precli/cli/main.py
precli/core/run.py

Adds two more progress indicators when targetting a github repo. One indicator tracks the downloading and another tracks the zipfile extraction.

More progress indicators

---

precli/core/argument.py
precli/core/utils.py
precli/parsers/python.py
precli/rules/python/stdlib/argparse_sensitive_info.py
precli/rules/python/stdlib/hashlib_weak_hash.py
precli/rules/python/stdlib/hmac_weak_hash.py
precli/rules/python/stdlib/http_server_unrestricted_bind.py
precli/rules/python/stdlib/http_url_secret.py
precli/rules/python/stdlib/socket_unrestricted_bind.py
precli/rules/python/stdlib/socketserver_unrestricted_bind.py
precli/rules/python/stdlib/xmlrpc_server_unrestricted_bind.py
tests/unit/rules/python/stdlib/hashlib/examples/hashlib_md5_as_identifier.py
tests/unit/rules/python/stdlib/hashlib/test_hashlib_weak_hash.py

Much of the code is now based on converting attributes and/or identifier nodes into strings to identify whether that string matches a suspicious call as part of a Rule.
However, the code needs to distinguish between a string representing an attribute/identifier and a true regular string.
To do this, a convenience utils class was added to detect true strings from tree-sitter node text. Luckily they appear different because they have extra quotes.
This should fix some critical false positive/negative cases where an identifier assignment was to a string and not a suspicious function.

Distinguish betwen strings and attributes

---

precli/parsers/python.py
tests/unit/rules/python/stdlib/hashlib/examples/hashlib_md5_importlib.py
tests/unit/rules/python/stdlib/hashlib/test_hashlib_weak_hash.py

The importlib.import_module module and function also needs to correctly handle the new format for "true" strings in an argument value. It needs to use value_str instead of value.

importlib.import_module also needs to handle string types

---

precli/parsers/python.py
precli/rules/python/stdlib/secrets_weak_token.py
tests/unit/rules/python/stdlib/secrets/examples/secrets_token_bytes_size_var.py
tests/unit/rules/python/stdlib/secrets/test_secrets_weak_token.py

It is possible for a variable to be used multiple times and even with multiple types prior to its use in the function call. This didn't work because the left hand side of the assignment would be resolved into its complete fully qualified function name.
However, it's also important to keep track of the identifier name in the symbol table in case it is reused. That way the value is properly overwritten.

Fix for cases of a reassignment of a variable

---

precli/rules/python/stdlib/hmac_timing_attack.py
tests/unit/rules/python/stdlib/hmac/examples/hmac_timing_attack.py
tests/unit/rules/python/stdlib/hmac/examples/hmac_timing_attack_class.py
tests/unit/rules/python/stdlib/hmac/examples/hmac_timing_attack_class_hexdigest.py
tests/unit/rules/python/stdlib/hmac/examples/hmac_timing_attack_compare_digest.py

The examples for the hmac timing attack code uses a return, but not inside a function. This would be a syntax error if the code was attempted to run.

Correct invalid examples for hmac timing attack

---

docs/rules.md
docs/rules/python/stdlib/hashlib-improper-prng.md
precli/rules/python/stdlib/hashlib_improper_prng.py
precli/rules/python/stdlib/hashlib_weak_hash.py
setup.cfg
tests/unit/rules/python/stdlib/hashlib/examples/hashlib_improper_prng_blake2b.py
tests/unit/rules/python/stdlib/hashlib/examples/hashlib_improper_prng_blake2s.py
tests/unit/rules/python/stdlib/hashlib/examples/hashlib_improper_prng_pbkdf2_hmac.py
tests/unit/rules/python/stdlib/hashlib/examples/hashlib_improper_prng_scrypt.py
tests/unit/rules/python/stdlib/hashlib/test_hashlib_improper_prng.py

Specifically in the hashlib module, it specifies that secure alternatives to the random module should be used for crypto functions.
This rule checks various hashlib functions where a salt is provided via an insecure random function such as random.randbytes() or ssl.RAND_bytes()
Closes #229

Add rule to check for improper random generator usage

---

precli/rules/python/stdlib/argparse_sensitive_info.py
tests/unit/rules/python/stdlib/argparse/examples/argparse_add_argument_default_action.py
tests/unit/rules/python/stdlib/argparse/test_argparse_sensitive_info.py

The default value for action when no value is passed is "store" which is the exact value we are trying to detect for issues. So if a program creates CLI arguments via add_argument with api-key or password arg and unset action, it needs to surface this as an issue.

Check for no action passed in argparse rule

---

precli/cli/main.py

This modifies the run of the CLI to only check for new PyPI updates to the package if a given target is a GitHub address or the output is designated to Gist. Both of these are remote, and so the cost to check an update (also remote) only runs in the same case.

Do update check only if git target or gist output

---

.github/dependabot.yml

Dependabot currently only looks for updates of the github-action versions. This change adds checks for PyPI dependency updates.

Add dependabot checks for PyPI packages

---

precli/rules/python/stdlib/hmac_weak_hash.py

This change adds suggested fixes for the hmac_weak_hash rule. So if someone uses md5 digest in the hmac call, it should suggest sha256.

Add suggested fixes for weak hashes in hmac function

---

precli/parsers/python.py
tests/unit/parsers/examples/importlib_import_module.py
tests/unit/parsers/test_python.py

If the name part of the parameter to import_module cannot be determined (in this case it was None), the code should not attempt to continue or put in symbol table.
Fixes #405

Fix traceback from usage of importlib.import_module

---

precli/parsers/python.py
tests/unit/parsers/examples/expression_list_assignment.py
tests/unit/parsers/test_python.py

There are some cases where the left and right hand sides of the assignment don't have equal number of arguments. This change ensures the node children have identical sizes to avoid this condition.
A longer term solution might be to handle star arguments.
Fixes #407

Fix for IndexError in an expression list assignment

---

precli/cli/main.py

This change adds the copyright and license to the --version CLI argument output. It also no longer uses the arg[0] as the program's name, following the recommendation of the GNU documentation on version output.
Closes #409

Add more detail to the --version output

---

precli/cli/main.py

This change adds distribution extension name and version to the --version CLI argument output. So if an extension is being used with this CLI, it should list it as long as it begins with "precli-".

Add extensions to the version output

---

precli/core/argument.py

This fixes the case when a call is analyzed that has a call as one of its arguments.
foobar("foo", bar())
Now the call in the argument list will resolve to an identifier node.

Resolve a call argument that is a call to its identifier

---

precli/parsers/java.py
precli/rules/java/stdlib/crypto_weak_cipher.py
tests/unit/rules/java/stdlib/javax_crypto/examples/cipher_aes_cbc.java
tests/unit/rules/java/stdlib/javax_crypto/examples/cipher_arcfour.java
tests/unit/rules/java/stdlib/javax_crypto/examples/cipher_blowfish_cbc.java
tests/unit/rules/java/stdlib/javax_crypto/examples/cipher_rc2.java
tests/unit/rules/java/stdlib/javax_crypto/examples/cipher_rc4.java
tests/unit/rules/java/stdlib/javax_crypto/examples/cipher_rc5.java
tests/unit/rules/java/stdlib/javax_crypto/test_crypto_weak_cipher.py

Add tests for aes, arcfour, blowfish, rc2, rc4, and rc5. This change also now properly handles a wildcard import.

Add more tests for java weak cipher rule

---

precli/core/call.py
precli/parsers/go.py
precli/parsers/java.py
precli/parsers/python.py

There are many differences in a call between Java, Go, and Python. As a result the Call class can't handle the differences. Instead, each parser should deal with those unique differences.

Make Call class more generic for all supported languages

---

precli/parsers/__init__.py
tests/unit/rules/java/stdlib/java_security/examples/MessageDigestMD5.java

It's possible for different rules define a wildcard that has the same key. As a result, this collison would overwrite the other.
This change fixes the collison by appending the wildcard value to the other.

Fix collison in rule wildcards

---

precli/parsers/java.py

The entry and exit of a class or method declaration should have a new symbol table.

Create sub-symbol tables on class and method declaration

---

docs/rules/go/stdlib/crypto-weak-cipher.md
docs/rules/go/stdlib/crypto-weak-hash.md
docs/rules/go/stdlib/crypto-weak-key.md
docs/rules/java/stdlib/java-security-weak-hash.md
docs/rules/java/stdlib/java-security-weak-key.md
docs/rules/java/stdlib/javax-crypto-weak-cipher.md

The Python docs have headers with slug, title, etc. So should the Go and Java docs

Go and Java docs should have similar headers as Python

---

docs/rules.md
docs/rules/java/stdlib/java-security-weak-random.md
precli/rules/java/stdlib/java_security_weak_random.py
setup.cfg
tests/unit/rules/java/stdlib/java_security/examples/SecureRandomDefault.java
tests/unit/rules/java/stdlib/java_security/examples/SecureRandomSHA1PRNG.java
tests/unit/rules/java/stdlib/java_security/test_weak_random.py

The usage of algorithm SHA1PRNG is considered weak and should be avoided.

Add rule for detection of weak random algorithm in SecureRandom

---

precli/rules/java/stdlib/java_security_weak_random.py

The weak random Java rule currently suggests a fix that tells the user to use the constructor insteead of getInstance method. As a result, the NoSuchAlgorithmException doesn't get thrown. So the fix would create code that no longer compiles.
This change now swaps the weak random algorithm with a strong one that is known to exists for all platforms.

Don't break codee with suggested fix

---

precli/rules/java/stdlib/java_security_weak_hash.py
precli/rules/java/stdlib/java_security_weak_random.py
tests/unit/rules/java/stdlib/java_security/examples/MessageDigestMD5Property.java
tests/unit/rules/java/stdlib/java_security/test_weak_hash.py

The algorithm string might have a None value if the parser cannot determine its actual value.
For example, in the added testcase, if a value goes through a Properties class, the parser does track this value.

Weak hash and weak random Java rules need to guard from none

---

docs/rules.md
precli/rules/java/stdlib/javax_servlet_http_insecure_cookie.py

The latest java rule reference link in the rules table has a typo thus given the users a broken link.

Fix broken link in rules table

---

docs/rules.md
docs/rules/java/stdlib/java-net-insecure-cookie.md
precli/rules/java/stdlib/java_net_insecure_cookie.py
setup.cfg
tests/unit/rules/java/stdlib/java_net/examples/HttpCookieSecureFalse.java
tests/unit/rules/java/stdlib/java_net/examples/HttpCookieSecureTrue.java
tests/unit/rules/java/stdlib/java_net/test_insecure_cookie.py

Similar to javax.servlet.http.Cookie, the java.net.HttpCookie is also a class whether the contents of the cookie can be marked secure. This rule advises to always set secure to true.

Add Java rule for insecure java.net.HttpCookie

---

README.rst

The path to hmac_timing_attack.py was incorrect. This change fixes that and adds the example output.

README example with wrong path

---

docs/getting-started.md

The Getting Started has examples with paths that don't exist. This change corrects those paths.

Correct the paths given in getting start examples

---

precli/parsers/python.py
tests/unit/parsers/examples/expression_list_assignment.py
tests/unit/parsers/examples/expression_list_assignment_uneven.py
tests/unit/parsers/test_python.py

When there is an assignment using a pattern_list and expression_list, the current code will iterate through each assignment. However, the current code assumes it can use context['node'], which is not the expected node during the parse.
```console
: Language(path, name) is deprecated. Use Language(ptr, name) instead.
warn("{} is deprecated. Use {} instead.".format(old, new), FutureWarning)
logging initialized
Working on file: tests/unit/parsers/examples/expression_list_assignment.py
Exception occurred when executing rules against tests/unit/parsers/examples/expression_list_assignment.py. Run "precli --debug tests/unit/parsers/examples/expression_list_assignment.py" to see the full traceback.
Exception string: cannot access local variable 'func_node' where it is not associated with a value …
```

Fix traceback raised on an expression list assignment

---

precli/core/run.py
precli/renderers/json.py

The SARIF output currently shows only the end_time of an innovation. This change will also add start_time. It also moves these times into the run object.

Add start_time to SARIF output

---

precli/parsers/__init__.py
precli/parsers/go.py
precli/parsers/java.py
precli/parsers/python.py

The tree-sitter child_by_field_name doesn't appear to return any non-None value for any of our parsers. Therefore, this change will just switch all code to use the new convenience function child_by_type.

Use child_by_type for all parsers

---

precli/core/symtab.py

Only the global (top-most) scope should have symbols visible to all inner scopes.
This changes the symbol table to no longer recursive search through parent symtabs and instead search current scope or global.
Future work should handle enclosed scope and global vs. nonlocal assignments (in Pyt have symbols
visible to all inner scopes.
This changes the symbol table to no longer recursive search through parent symtabs and instead search current scope or global.
Future work should handle enclosed scope and global vs. nonlocal assignments (in Python))

Fix how scoped variables accessed in symbol table

---

tests/unit/rules/python/stdlib/http/examples/http_server_http_server.py
tests/unit/rules/python/stdlib/http/examples/http_server_threading_http_server.py
tests/unit/rules/python/stdlib/xmlrpc/examples/xmlrpc_server_doc_xml_rpc_server.py
tests/unit/rules/python/stdlib/xmlrpc/examples/xmlrpc_server_simple_xml_rpc_server.py

Some of the test cases use code defined in fucntions but would not execute unless from some other module calling that function.
This change updates each of these tests to add a main guard that calls the function.

Update some tests so they are runnable

---

scripts/main.py

The entry_point defined in the setup.cfg is precli.cli.main, therefore there is no reference or need to use the scripts/main.py file.

Remove the unnecessary scripts directory and contents

---

precli/renderers/json.py

The defaultConfiguration object defines a few default settings such as whether the rule is enabled and what the default level is.

Add defaultConfiguration in SARIF output

---

precli/core/run.py

Legacy use of string substitution found. Switch it to f-string.

Use f-string instead of string substitution

---

precli/core/argument.py
precli/core/artifact.py
precli/core/call.py
precli/core/comparison.py
precli/core/config.py
precli/core/fix.py
precli/core/location.py
precli/core/metrics.py
precli/core/result.py
precli/core/run.py
precli/core/suppression.py
precli/core/tool.py
precli/core/utils.py
precli/parsers/__init__.py
precli/rules/__init__.py

Any function that already uses types, doesn't really need to redundantly have docstrings that denote what the parameter or return type is.

Remove some docstring comments on return and params

---

precli/core/artifact.py
precli/core/run.py
precli/parsers/__init__.py
precli/parsers/go.py
precli/parsers/java.py
precli/parsers/python.py

Python files default to be encoded in UTF-8, but they don't have to be. At the head of Python file, you can define the encoding.
This change modifies the convenience function of the Node to return a str object in the encoding of the file, honoring this header and defaulting to utf-8.
See:
https://docs.python.org/3/howto/unicode.html#unicode-literals-in-python-source-code
Fixes: #468
Fixes: #473
Fixes: #472

Handle non-UTF-8 encoding files

---

precli/rules/python/stdlib/secrets_weak_token.py
tests/unit/rules/python/stdlib/secrets/examples/secrets_token_hex_nbytes_unknown.py
tests/unit/rules/python/stdlib/secrets/test_secrets_weak_token.py

If the nbytes argument to token_hex cannot be determined from the symbols, analysis should not fail with an error, and just continue.
Fixes: #474

Fix unknown value for nbytes

---

precli/cli/main.py
precli/core/run.py
precli/renderers/__init__.py
precli/renderers/detailed.py
precli/renderers/json.py
precli/renderers/markdown.py
precli/renderers/plain.py

This change makes use of a more global rich.console Console for output. The console object is passed to renderers instead of created in them.
The unexpected exceptions and errors are now printed with rich. This makes for better readability.

Nicer output using rich.console

---

precli/cli/main.py
precli/core/run.py
precli/core/tool.py

Currently parsers are being created twice, once in CLI main and once in the run module.
This change moves it only in the run module.

Avoid init of parsers twice

---

precli/parsers/__init__.py
precli/parsers/python.py

Precli is printing out FutureWarnings from tree-sitter about how it is initialized. The warning looks like the following:
```
FutureWarning: Language(path, name) is deprecated. Use Language( ptr, name) instead.
```
Similarly, the re module is also printing out a FutureWarning when precli analyzes cpython test code. It looks like the following:
```
FutureWarning: Possible set difference at position 4
FutureWarning: Possible set intersection at position 6
FutureWarning: Possible set union at position 6
FutureWarning: Possible set symmetric difference at position 5
FutureWarning: Possible nested set at position 3
```
In both cases, precli has been changed to suppress and ignore these warnings for now. There is probably no fix for the re module one, but I expect a fix for the tree-sitter …

Suppress FutureWarnings from tree-sitter and re modules

---

precli/core/run.py

The code should not load a file's contents unless it has already determined there is a parser available to parse the given file extension. Otherwise, the performance is degraded loading files in which nothing is parsed.

Delay reading of file contents until parser decided

---

precli/core/run.py

It's a bit more logical to order the file as the first argument of parse_file. For the partial, you need to use keyword args if args to come after the iterable.

Nit: Rearrange args to partial

---

precli/cli/main.py
precli/core/run.py

During the discovery of the files when given a recursive directory to parse, build a list of artifacts only with files of extensions we can parse.

Filter the list of artifacts during discovery

---

precli/cli/main.py
precli/core/run.py
precli/parsers/__init__.py
precli/parsers/go.py
precli/parsers/java.py
precli/parsers/python.py

This change returns a rule ID defined as <parser rule prefix>000.
This is follow on change for returning syntax and other various
errors as a result instead of something different.
Signed-off-by: Eric Brown <eric.brown@securesauce.dev>

Return a rule ID for syntax and other errors

---

precli/cli/main.py

The Progress class of Rich supports showing progress as download progress in bytes (MB, GB, etc). Ideally we would also show the progress as a ratio to the total zipball file size, but unforutnately the Content-Length header is not reliably returned.
The progress of the extraction was also modified to show progress in terms of files extracted vs. the total files in the zip.

Show download progress in file size

---

setup.cfg

The docs have been migrated to mkdocs, so there is no longer any need for sphinx settings.

Remove unnecessary sphinx config in tox.ini

---

precli/rules/python/stdlib/argparse_sensitive_info.py
tests/unit/rules/python/stdlib/argparse/examples/argparse_add_argument_token.py
tests/unit/rules/python/stdlib/argparse/test_argparse_sensitive_info.py

Sometimes --token is used on the command line to pass a secret token. Therefore this rule should also check for it.
Closes #503

Add --token to argparse rule

---

precli/cli/main.py
requirements.txt

The code to check for a new version of precli has been problemmatic. It's also not strictly required feature. So this commit removes it for now. It might be revisited later.

Remove the newer version check

---

precli/rules/python/stdlib/http_server_unrestricted_bind.py
precli/rules/python/stdlib/socket_unrestricted_bind.py
precli/rules/python/stdlib/socketserver_unrestricted_bind.py
precli/rules/python/stdlib/xmlrpc_server_unrestricted_bind.py

For rules that detect unrestricted binds, like 0.0.0.0, a suggested fix can be made to switch to 127.0.0.1 or ::1.
Closes #445

Suggest using localhost address as fix

---

precli/parsers/python.py

An assignment is assigning a value to an identifier. Resolving the identifier can lead to issues when putting into the symbol name as the identifer is expected to be a name. This is what occurred when trying to add dicts to the parser's resolve(). The same would probably occur for tuple and any other non-string identifier value that it would get resolved to.
The visit_comparison_operator is still resolving left_hand, but in its case, its not put into the symbol table. It's also needed to compare left and right for things like timing attack rule that checks whether the left and right are the same type.

Don't do a resolve on the left hand side of an assignment

---

precli/core/argument.py
precli/core/artifact.py
precli/core/cwe.py
precli/core/symtab.py
precli/parsers/__init__.py
precli/parsers/go.py
precli/parsers/java.py
precli/parsers/python.py
precli/rules/__init__.py

Pyright returns numerous typing errors in the code base. This change cleans up a significant number of them.

Fix up some of the typing errors

---

mkdocs.yml
precli/rules/python/stdlib/crypt_weak_hash.py

Some rule docs include mulitple examples. In those cases, it's better to use a tabbed block so the page looks cleaner.

Use tabbed code blocks when there are multiple examples

---

.pre-commit-config.yaml
docs/index.md
docs/man/precli.md
mkdocs.yml

* Make use of grids to display information in an easier-to-read format
* Convert man page rst into markdown and provide link to it
* The grid links to the getting started, CLI reference, rules, and license

Pretty up the home index for the docs

---

docs/stylesheets/extra.css
mkdocs.yml
precli/rules/python/stdlib/argparse_sensitive_info.py

Switches the default git-alt icon to GitHub as the link to the repo.

Use GitHub icon for docs link

---

docs/javascripts/tablesort.js
mkdocs.yml

The mkdocs-material docs format supports making tables alpha sortable with some changes.
https://squidfunk.github.io/mkdocs-material/reference/data-tables/#sortable-tables-mkdocsyml

Make doc tables sortable

---

docs/man/precli.md
precli/cli/main.py
precli/parsers/__init__.py
precli/rules/__init__.py

Allow the user to specify a rule list range, such as
--enable=PY002-PY005
Also, the enabled and disabled CLI arguments are now made mutually exclusive.
Closes: #531

Allow rule ranges on command line

---

precli/parsers/python.py

The resolve function of the python parse currently only handles base 10 decimal inteegers. This change will include alternative base forms of hexadecimal, ordinal, and binary forms.

Resolve hex, ord, and binary forms of an integer

---

docs/man/precli.md
precli/cli/main.py
precli/core/loader.py
precli/core/run.py
setup.cfg

The renderers should ideally be loaded via the extension mechanism rather than hard-coding the load of each class.
This also enables the ability to add future renderers without changes to the code that loads them.
Closes #541

Use extension loader to load renderers

---

precli/parsers/__init__.py
requirements.txt

* Updates to tree-sitter 0.22.3
* In order to accomplish this update, needed to switch to pip installing of git releases instead of PyPI since the binaries MacOS ARM are missing.
* Removes the need to suppress the warning from tree-sitter

Bump to latest version of tree-sitter

---

README.rst
docs/getting-started.md
requirements.txt

The tree-sitter-python on PyPI unfortunately doesn't include the binaries for Arm based MacOS. As a result, the only way to get it is from the github repo.
This change updates the instructions to advise the user how to install this added dependency that won't get installed from pip fetching from PyPI.
The requirements.txt is also updated to use PyPI in all cases except if Arm based MacOS.

tree-sitter-python requires manual install on arm macOS

---

precli/core/argument.py
precli/core/artifact.py
precli/core/call.py
precli/core/fix.py
precli/core/location.py
precli/core/result.py
precli/core/suppression.py
precli/parsers/__init__.py
precli/rules/__init__.py

This change makes use of typing.Optional to resolve errors where pyright complains about a <type | None>.

More typing error fixes

---

.readthedocs.yaml

Read-the-docs has an option to use the latest ubuntu LTS release. Switching to this option is easier to maintain as new ubuntu versions get released.

Use ubuntu latest for readthedocs build

---

README.rst

In order to make the example scenario more clear, this change also adds the example code so stakeholders can see what code was analyzed and how the result relates.

Add example code to Readme for clear example

---

README.rst

This change makes the README look less cluttered.

Move README build badge above divider

---

precli/parsers/python.py
precli/rules/__init__.py
tests/unit/rules/python/stdlib/argparse/examples/argparse_add_argument_token.py
tests/unit/rules/python/stdlib/socket/examples/socket_socket_bind.py

This change moves the wild card processing from the particular parser into the rule class. The analyze_node() call mechanism is being reused to do wildcard processing.
This is a strategy that could later be used to actually load identifiers of an import into the symbol table as they are loaded.

Refactor how wildcard imports are processed

---

precli/parsers/__init__.py
precli/parsers/java.py
precli/parsers/python.py
precli/rules/__init__.py

Need to do the same refactoring in the Java parser. Also, the base Parser class no longer needs to combine all the wildcards from various rules.

Second pass at refactoring wildcard logic

---

precli/rules/python/stdlib/os_loose_file_perm.py

This change will fix edge cases where the argument has a value of None or str and gets into conditions that expected as default mode argument.

Fix raised exceptions in edge cases of incorrect permissions

---

docs/rules.md
docs/rules/python/stdlib/pathlib-loose-file-perm.md
precli/rules/python/stdlib/pathlib_loose_file_perm.py
setup.cfg
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_IXOTH.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_S_IXOTH.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_S_S_IXOTH.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_o111_binop_wildcard.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_o644.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_o7.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_o755_binop_stat.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_o760.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_o770.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_o776.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_o777.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_stat_S_IXOTH.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_chmod_x1ff.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_lchmod_o227.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_mkdir_default.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_mkdir_o750_binop.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_touch_default.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_touch_o750_binop.py
tests/unit/rules/python/stdlib/pathlib/test_pathlib_loose_file_perm.py

This rule adds checks for usage of pathlib.Path functions where a file mode can be passed and the file mode is considered loose permissions. It checks functions chmod, lchmod, mkdir, and touch.
Unit tests and documentation also added.
Closes: #217

New rule for pathlib.Path usage with loose permissions

---

precli/rules/python/stdlib/pathlib_loose_file_perm.py

A copy-and-paste error where PY036 should be PY037 for the pathlib loose permissions rule.

Fix for typo in pathlib rule example output

---

precli/cli/main.py
precli/core/run.py

The Run class doesn't need a rich.Console instance for any reason. This change removes it and cleans up the calls to run.

Remove the unnecessary console object on Run

---

precli/core/run.py

The Run class should only load data from the artifact file if the contents is None. This in particular affects services such as Precaution. It also prevents an error when a file is loaded as stdin.

Only load file if artifact content is none

---

precli/parsers/__init__.py
precli/parsers/go.py
precli/parsers/java.py
precli/parsers/python.py

This change prevents another opening and reading of a file when trying to determine the file encoding for a file. In some cases such as when run under Precaution, the file doesn't exist locally anyway, so it needs to use what is in the artifact contents.

Get file encoding using artifact contents

---

README.rst
docs/getting-started.md
requirements.txt

Updates to:
- tree-sitter 0.23.0
- tree-sitter-go 0.23.0
- tree-sitter-python 0.23.0
Note, tree-sitter-java has no new release.

Update to the latest tree-sitter

---

precli/parsers/python.py

It's possible that part of the expression of an augmented assignment doesn't resolve to an int. In such a case, the current code tries to bitwise compute the values anyway. This of course results in a syntax error.
This fix in this change ensures both left and right side of the expression resolve to an int value. Other bitwise computable values in the future could also be added.

Fix augmented assignment

---

docs/rules.md
docs/rules/python/stdlib/os-setuid-root.md
precli/core/cwe.py
precli/rules/python/stdlib/os_setuid_root.py
setup.cfg
tests/unit/rules/python/stdlib/os/examples/os_setuid_0.py
tests/unit/rules/python/stdlib/os/examples/os_setuid_1000.py
tests/unit/rules/python/stdlib/os/examples/os_setuid_root.py
tests/unit/rules/python/stdlib/os/test_os_setuid_root.py

Setting the current process to user ID 0 (root) elevates the process to run as root which can be particularly risky for an application.
Partially-resolves #587

New python rule to check for setuid(0)

---

docs/rules.md
docs/rules/go/stdlib/syscall-aetuid-root.md
precli/rules/go/stdlib/syscall_setuid_root.py
setup.cfg
tests/unit/rules/go/stdlib/syscall/examples/syscall_setuid_0.go
tests/unit/rules/go/stdlib/syscall/examples/syscall_setuid_500.go
tests/unit/rules/go/stdlib/syscall/test_syscall_setuid_root.py

Similar to rule PY038, this rule checks Go code for syscall Setuid where the uid is set to 0 (aka root user).
Rule ID: GO004
Closes: #587

New Golang rule to check for Setuid to root user

---

precli/rules/go/stdlib/crypto_weak_cipher.py
precli/rules/go/stdlib/crypto_weak_hash.py
precli/rules/go/stdlib/crypto_weak_key.py

No need to pass empty dict as the wildcards parameter of the initialization of a Rule.

Remove unnecessary init of wildcards

---

precli/rules/go/stdlib/syscall_setuid_root.py

There are some leftover typos as a result of copying from the Python os.setuid rule (PY038). Namely, the function is Setuid not setuid. And not os.setuid, but syscall.Setuid

Cleanup copy-and-paste typos in syscall.Setuid rule

---

precli/rules/go/stdlib/syscall_setuid_root.py

Fix typo in the example output

---

docs/rules.md
docs/rules/python/stdlib/socket-no-timeout.md
precli/core/cwe.py
precli/rules/python/stdlib/ftplib_unverified_context.py
precli/rules/python/stdlib/socket_no_timeout.py
setup.cfg
tests/unit/rules/python/stdlib/socket/examples/socket_create_connection.py
tests/unit/rules/python/stdlib/socket/examples/socket_create_connection_timeout_5.py
tests/unit/rules/python/stdlib/socket/examples/socket_create_connection_timeout_none.py
tests/unit/rules/python/stdlib/socket/test_socket_no_timeout.py

This rule checks for cases where socket.create_connection and a parameter for the timeout is not set. If set to None or unset, the blocking socket can potentially hang indefinitely.
Closes: #519

New rule to check socket.create_connection with no timeout

---

precli/rules/python/stdlib/socket_no_timeout.py
tests/unit/rules/python/stdlib/socket/examples/socket_create_connection_timeout_0.py
tests/unit/rules/python/stdlib/socket/test_socket_no_timeout.py

The SocketNoTimeout rule also needs to check for timeout values of 0 or less than 0 which also equate to no timeout. The value can also be of type float.

SocketNoTimeout needs to check for 0 and negative timeouts

---

precli/rules/python/stdlib/smtplib_no_timeout.py
precli/rules/python/stdlib/socket_no_timeout.py
setup.cfg
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_lmtp_timeout_none.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_auth.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_context_mgr.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_login.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_no_timeout.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_ssl.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_ssl_context_as_var.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_ssl_context_none.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_ssl_context_unset.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_ssl_no_timeout.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_starttls.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_starttls_context_as_var.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_starttls_context_none.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_starttls_context_unset.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_timeout_5.py
tests/unit/rules/python/stdlib/smtplib/test_smtplib_no_timeout.py

This rule enforces that a timeout parameter must be provided when instantiating `smtplib.SMTP`, `smtplib.SMTP_SSL`, or `smtplib.LMTP` to prevent the possibility of indefinite blocking.

New rule to check for no timeout use in smtplib

---

docs/rules.md
docs/rules/python/stdlib/smtplib-no-timeout.md

The doc for smtplib_no_timeout rule was missing. Thus this commit creates the autodoc for it and adds to the list of rules.

Add doc for new smtplib no timeout rule

---

precli/rules/python/stdlib/smtplib_unverified_context.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_starttls_context_none.py

The context passed to starttls function is always a kwarg and not a positional. As such, the rule needs to check for it in that way.

The smtplib starttls context arg is always a kwarg

---

docs/rules.md
docs/rules/python/stdlib/imaplib-no-timeout.md
precli/rules/python/stdlib/imaplib_no_timeout.py
precli/rules/python/stdlib/smtplib_no_timeout.py
setup.cfg
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_authenticate.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_context_mgr.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_login.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_login_cram_md5.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_no_timeout.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_ssl.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_ssl_context_as_var.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_ssl_context_none.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_ssl_context_unset.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_ssl_timeout_none.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_starttls_context_as_var.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_starttls_context_none.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_starttls_context_unset.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_timeout_5.py
tests/unit/rules/python/stdlib/imaplib/test_imaplib_no_timeout.py

New rule PY041.
When imaplib.IMAP4 or IMAP4_SSL are used without specifiying a timeout, the connections have the potential to block forever. The default timeout is the global socket timeout setting which is None by default (effectively no timeout).

New Python rule to check for imaplib use without a timeout

---

docs/rules.md
docs/rules/python/stdlib/poplib-no-timeout.md
docs/rules/python/stdlib/telnetlib-no-timeout.md
precli/rules/python/stdlib/telnetlib_no_timeout.py
setup.cfg
tests/unit/rules/python/stdlib/telnetlib/examples/telnet.py
tests/unit/rules/python/stdlib/telnetlib/examples/telnetlib_telnet.py
tests/unit/rules/python/stdlib/telnetlib/examples/telnetlib_telnet_context_mgr.py
tests/unit/rules/python/stdlib/telnetlib/examples/telnetlib_telnet_no_timeout.py
tests/unit/rules/python/stdlib/telnetlib/examples/telnetlib_telnet_open_timeout_none.py
tests/unit/rules/python/stdlib/telnetlib/examples/telnetlib_telnet_timeout_5.py
tests/unit/rules/python/stdlib/telnetlib/test_telnetlib_no_timeout.py

PY044
The Telnet class and open function on the object has timeout arguments that if undefined or set to None tell the library to use the global default timeout which has a default of None which has the effect of blocking forever.

New Python rule checks use of Telnet with no timeout

---

docs/rules.md
docs/rules/python/stdlib/ftplib-no-timeout.md
precli/rules/python/stdlib/ftplib_no_timeout.py
setup.cfg
tests/unit/rules/python/stdlib/ftplib/examples/ftplib_ftp_connect_timeout_none.py
tests/unit/rules/python/stdlib/ftplib/examples/ftplib_ftp_no_timeout.py
tests/unit/rules/python/stdlib/ftplib/examples/ftplib_ftp_tls_no_timeout.py
tests/unit/rules/python/stdlib/ftplib/test_ftplib_cleartext.py
tests/unit/rules/python/stdlib/ftplib/test_ftplib_no_timeout.py

PY045
The ftplib classes FTP and FTP_TLS have timeout arguments that defaul to the global timeout which defaults to None or blocking forever. FTP.connect method similarly has a timeout argument. Its important to always have a reasonable timeout set so the connections don't block forever.

New Python rule checks ftplib use without a timeout

---

docs/rules.md
docs/rules/python/stdlib/ssl-no-timeout.md
precli/rules/python/stdlib/ssl_no_timeout.py
setup.cfg
tests/unit/rules/python/stdlib/ssl/examples/get_server_certificate_no_timeout.py
tests/unit/rules/python/stdlib/ssl/examples/get_server_certificate_timeout_5.py
tests/unit/rules/python/stdlib/ssl/examples/get_server_certificate_timeout_none.py
tests/unit/rules/python/stdlib/ssl/test_ssl_no_timeout.py

The ssl.get_server_certificate function has a timeout parameter that defaults to the global timeout which itself defaults to None. When the value is None, the socket blocks forever.
Note: the timeout parameter wasn't added till Python 3.10. To fix this on earlier Python versions, someone would need to adjust the global timeout value.
PY046

New Python rule checks for ssl use with no timeout

---

precli/parsers/__init__.py
precli/parsers/python.py
precli/rules/python/stdlib/ftplib_no_timeout.py
precli/rules/python/stdlib/imaplib_no_timeout.py
precli/rules/python/stdlib/nntplib_no_timeout.py
precli/rules/python/stdlib/poplib_no_timeout.py
precli/rules/python/stdlib/smtplib_no_timeout.py
precli/rules/python/stdlib/socket_no_timeout.py
precli/rules/python/stdlib/ssl_no_timeout.py
precli/rules/python/stdlib/telnetlib_no_timeout.py
tests/unit/rules/python/stdlib/ftplib/examples/ftplib_ftp_timeout_global.py
tests/unit/rules/python/stdlib/ftplib/test_ftplib_no_timeout.py
tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_timeout_global.py
tests/unit/rules/python/stdlib/imaplib/test_imaplib_no_timeout.py
tests/unit/rules/python/stdlib/nntplib/examples/nntplib_nntp_timeout_global.py
tests/unit/rules/python/stdlib/nntplib/test_nntplib_no_timeout.py
tests/unit/rules/python/stdlib/poplib/examples/poplib_pop3_timeout_global.py
tests/unit/rules/python/stdlib/poplib/test_poplib_no_timeout.py
tests/unit/rules/python/stdlib/smtplib/examples/smtplib_smtp_timeout_global.py
tests/unit/rules/python/stdlib/smtplib/test_smtplib_no_timeout.py
tests/unit/rules/python/stdlib/socket/examples/socket_create_connection_timeout_global.py
tests/unit/rules/python/stdlib/socket/test_socket_no_timeout.py
tests/unit/rules/python/stdlib/ssl/examples/get_server_certificate_timeout_global.py
tests/unit/rules/python/stdlib/ssl/test_ssl_no_timeout.py
tests/unit/rules/python/stdlib/telnetlib/examples/telnetlib_telnet_timeout_global.py
tests/unit/rules/python/stdlib/telnetlib/test_telnetlib_no_timeout.py

Python code can use a function socket.setdefaulttimeout() to set a global timeout value for all network classes functions that use it. Therefore, the Precli rules that check for an undefined timeout should honor this global value.
Note, currently this code will only recognize a global value of the timeout on a per-file basis. Later an inter-file global state of variables should be maintained, but this requires better analyzing of the code in the expected order of execution.

Enhance timeout rules ot honor the global timeout

---

precli/cli/main.py

Rather than manually updating the copyright year every year in the code, this change makes it so it just uses the current year date to fill in the copyright string.

Automatically update the copyright year

---

docs/man/precli.md

Some leftover artifacts when the man page used RST format instead of markdown.
* Replace "::" with ":"
* Add newline after .preignore

Some nit fixing up of the man page

---

precli/core/run.py

This simple change adds logging message of the start and end of a run invocation.

Add some logging of the start and end of the run

---

docs/getting-started.md
docs/requirements.txt
mkdocs.yml

The mkdocs macros plugin also us to add variables in the markdown, including some predefined variables such as those from git metadata.
In this case, the git short tag is used to automatically have the revision tag up-to-date with the latest version in the pre-commit config.
https://github.com/fralau/mkdocs-macros-plugin
https://mkdocs-macros-plugin.readthedocs.io/en/latest/git_info/
https://jimandreas.github.io/mkdocs-material/reference/variables/#using-predefined-variables

Add support of mkdocs macros

---

precli/rules/python/stdlib/argparse_sensitive_info.py

The argparse rule was the only rule with a divider after the title. This change simply removes it for consistent look and feel to the docs.

Remove inconsistent divider in argparse rule

---

mkdocs.yml

Mkdocs is complaining about all the rule docs that are not listed in the navigation tree. To remedy this, mkdocs allows a not_in_nav directive to include these non-nav based docs.

Fix up not_in_nav errors from mkdocs

---

precli/rules/python/stdlib/os_loose_file_perm.py
precli/rules/python/stdlib/pathlib_loose_file_perm.py
tests/unit/rules/python/stdlib/os/examples/os_mkdir_default.py
tests/unit/rules/python/stdlib/os/examples/os_mkfifo_default.py
tests/unit/rules/python/stdlib/os/examples/os_mknod_o666_binop.py
tests/unit/rules/python/stdlib/os/examples/os_open_default.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_mkdir_default.py
tests/unit/rules/python/stdlib/pathlib/examples/pathlib_touch_default.py

Two Python loose permission rules will return results when a function is used with a default permission mode that is considered risky.
However, these rules were not accounting for the umask that is typically set in the operating system and Python honors when calculating the effective mode.
This change applies an assumed umask of 0o022, even though it can vary to calculate effective modes for cases when the default mode of a function is used.
If a mode value is passed to the function, it still uses that mode argument as the mode to evaluate.

Honor umask in calculating effective mode

---

.github/workflows/unit-test.yml
requirements.txt

This change adds Python 3.13 to the test matrix. Even though it fails for now, better to start testing early and flush out bugs where possible.

Add Python 3.13 to unit test matrix

---

setup.cfg
tox.ini

Official tag the precli classifier to show support of Python 3.13 now that testing works successfully.

Show support of Python 3.13

---

.github/workflows/unit-test.yml
setup.cfg
setup.py
tox.ini

Precli already supports 3.12 and 3.13. It should easily also be able to support 3.11.
This should help adoption by supporting more versions of Python.

Add support for Python 3.11

---

README.rst

Update the instructions in the README about the installation of precli. It should state it requires 3.10+.

Update README requests Python 3.10+

---

precli/core/redos.py
precli/core/run.py
precli/core/symtab.py

Fixes a traceback caused by using a new datetime.UTC attribute not availabe in Python 3.10.
This also switches the try-exept ImportError logic with specific sys.version_info conditionals in the importing so its obvious what Python version affects that import.
Fixes #630

Fix some bugs using Python 3.10

---

docs/index.md

Technically, BSL is not open source according to OSI. As such, this change updates that statement to put Source Available, a more accurate description of the license.

Replace open source with source available

---

README.rst

No need to note which python version is needed to install as now Precli supports all non end-of-life versions.

Remove minimum python version text

---

precli/rules/python/stdlib/nntplib_no_timeout.py

Fix typo in the nntplib no timeout docstring

---

.readthedocs.yaml

Instead of hardcoding the version of Python, use the special "latest" keyword to always use the latest.

Always use latest python version

---

precli/rules/python/stdlib/assert.py
tests/unit/rules/python/stdlib/assert/examples/assert_test_func.py
tests/unit/rules/python/stdlib/assert/test_assert.py

For several Python test frameworks, the assert builtin is required to validate the test. Precli should avoid showing results for this condition since this isn't the use case the rule is trying to find.
Fixes: #638

Direct assert rule to ignore asserts in test functions

---

precli/rules/python/stdlib/assert.py
tests/unit/rules/python/stdlib/assert/test_assert.py

The point of the assert rule is to catch scenarios where Python builtin assert is used to guard or as a conditional in functions and not realize that running Python with optimizations (-O) would remove those assert statements.
However, in practice, its unlikely folks use the optimize compile option as it doesn't provide much "optimization" anyway. Frankly it does very very little. Therefore this change defaults the assert rule to disabled to cut down on noise and probably false positives.

Default the assert rule to be disabled

---

setup.cfg

This change adds more links to the project_urls of setuptools so that PyPI renders them.
It adds:
* documentation link
* issues link
* source code link

Add more project urls

---

README.rst

Feels somewhat redundant to have "To install precli". This change drops "precli"

Nit change to install part of README

---

precli/cli/main.py

Turns out that the --no-color argument had no effect. This change sets the Rich console with the no-color value passed from the commande line and from the environment variable (new).

Fix the no_color command line argument

---

setup.cfg

The PyPI warehouse code will display a special icon for project_urls defined for Slack, among other things.

Add slack link to PyPI

---

setup.cfg

Seems like PyPI doesn't display links that don't have a trailing slash in the URL.

Add trailing slash to project_url links

---

precli/renderers/json.py

The importlib.metadata.distributions is a feature added in 3.10. As a result, the code used to find extensions won't work in 3.9.
This fix disables the SARIF output of listing extensions in Python 3.9.
Fixes: #649

importlib metadata distributions not available in Py3.9

---

precli/parsers/python.py

The existing pattern to match whether the code analyzed was testing code was a little too frequent. At the very least it would always match the example code snippets in the tests of precli itself. And we can't have instructions that inform users to run precli against those examples if they always get ignored.
So this change changes the matching algorithm to filter out testing code only if all conditions are met, instead of just one. So the python file needs to be a directory path with "tests", filename beginning with "tests_", and in a function name starting with "test_".
In the future, these checks on whether it is test code or not need to be configurable in a precli configuration file of sorts.

Change the pattern to match for testing code

---

precli/rules/go/stdlib/crypto_weak_key.py
precli/rules/python/stdlib/ssl_context_weak_key.py

To be more consistent, this commit changes the config names of some of the weak key parameters. This enables customization based on the algorithm, RSA, DSA, EC the thresholds on the key size.

Slight naming change to the weak key rules config

---

precli/cli/init.py
precli/rules/__init__.py
precli/rules/go/stdlib/crypto_weak_key.py
precli/rules/java/stdlib/java_security_weak_hash.py
precli/rules/java/stdlib/java_security_weak_key.py
precli/rules/java/stdlib/javax_crypto_weak_cipher.py
precli/rules/python/stdlib/argparse_sensitive_info.py
precli/rules/python/stdlib/http_url_secret.py
precli/rules/python/stdlib/os_loose_file_perm.py
precli/rules/python/stdlib/pathlib_loose_file_perm.py
precli/rules/python/stdlib/secrets_weak_token.py
precli/rules/python/stdlib/ssl_context_weak_key.py
requirements.txt
setup.cfg

This new CLI enables a user to create a default config file (default to .precli.toml) in the current directory.
This config file is available for users to customize the precli tool and its rules.

Command line to create a .precli.toml default config file

---

precli/cli/init.py

Many Python projects support a pyproject.toml file, so its important to support it as a special output file.
If pyproject.toml is passed, precli-init will update the file with a tool.precli section and its configuration options.
This change also prompts to overwrite existing files. In addition the enabled vs. disabled rules is now part of a list rather than option on each rule section. This makes it easier to customize since most users would prefer to maintain a list rather than updating each section.

Support writing to pyproject.toml

---

precli/parsers/python.py

Running:
precli -r tests
Yields the following error:
TypeError: all() takes exactly one argument (3 given)
The recent change to is_test_code() is not using a collection passed to the all() function.

Fix CLI fails when running on the tests

---

precli/cli/main.py
precli/core/run.py
precli/parsers/__init__.py
tests/unit/rules/test_case.py

This change fully implements the processing of custom configuration given via toml files. So in effect, not just the enabled or disabled, but also the level and parameters can be overwritten.

Honor all configuration passed via toml files

---

precli/cli/main.py

This change moves the validation of the config file earlier in the setup of the arg parser. The argparse library itself is validating whether the file exists, so seems appropriate to also validate whether the file is a proper toml config file early as well.

Refactor the CLI checking of config arguments

---

precli/cli/main.py
tests/unit/cli/test_main.py

A user should be prompted if they attempt to overwrite an existing file that was specified as part of the -o output file.
There should also be unit testing around this behavior.

Add validation on the specified output file

---

precli/cli/main.py
tests/unit/cli/test_main.py

This change introduces unit test function for the output of the "precli --version" command.

Add unit test of the version argument to the CLI

---

precli/cli/init.py
tests/unit/cli/test_init.py
tests/unit/cli/test_main.py

This change tests some of the output of precli-init, specifically around the -o argument to ensure the file doesn't already exist or can't be written to.

Add unit test for precli-init command

---

precli/cli/main.py
tests/unit/cli/test_main.py

This change nicely checks for non-existant files and directories given as targets to precli. It utilizes argparse error() function for consistency with other validation mechanisms.
Fixes: #497

Add checking for files given that don't exist

---

tests/unit/cli/test_main.py

The CLI doesn't support rendering in multiple formats at once. Therefore you can specified more than one renderer for the output.

Add unit test for invalid multiple renderers given

---

tests/unit/cli/test_main.py

This unit test verifies that the enable and disable arguments can't be specified at the same time.

Add unit test of mutually exclusive enable and disable

---

precli/cli/main.py
precli/core/loader.py
precli/targets/__init__.py
precli/targets/file.py
precli/targets/github.py
setup.cfg

In order to make the code more cleanly pluggable. This change moves the discovery of files for both local and github sources into extensions. This would also permit adding other extensions for other types of sources.

Move the github target logic into an extension

---

precli/cli/init.py
precli/cli/main.py
tests/unit/cli/test_init.py
tests/unit/cli/test_main.py

The output option was broken in such that argparse would create the file if it didn't exist, then the code would additionally check if the file exist, which it would.
This change removes the overwrite checking code and simply changes argparse to error if the file already exists. It will be up to the user to specify a different file or delete the existing.

Fix the output option

---

precli/cli/main.py
precli/renderers/__init__.py
precli/renderers/detailed.py
precli/renderers/json.py
precli/renderers/markdown.py
precli/renderers/plain.py
tests/unit/cli/test_main.py

This change fixes --gist argument which was raising a traceback. Also adds a unit test of the condition where --gist is specified but GITHUB_TOKEN is undefined.
```
Traceback (most recent call last):
File "/Users/ericwb/workspace/precli/.tox/py313/bin/precli", line 8, in <module>
sys.exit(main())
~~~~^^
File "/Users/ericwb/workspace/precli/precli/cli/main.py", line 306, in main
create_gist(file, renderer)
~~~~~~~~~~~^^^^^^^^^^^^^^^^
File "/Users/ericwb/workspace/precli/precli/cli/main.py", line 238, in create_gist
"files": {filename: {"content": file_content}},
^^^^^^^^
UnboundLocalError: cannot access local variable 'filename' where it is not associated with a value
```

Fix --gist argument failure

---

precli/cli/main.py

Simply replace explicit checking for status code of 201 for response.ok. Makes code a little simpler.

Use response.ok instead of specific code

---

precli/__main__.py
precli/cli/main.py
tests/unit/cli/test_main.py

* Add unit test of the recursive flag
* Be sure to call sys.exit in main, even when 0
* replace the need to chdir by passing full paths in tests

Fix up the CLI main unit tests

---

precli/cli/main.py
tests/unit/cli/test_main.py

If results are found, return an exit code of 1. Return 0 otherwise.

Set exit code to 0 or 1 based on results

---

precli/cli/main.py
precli/targets/pypi.py
setup.cfg

Using the distribution utils extension mechanism, creates a new extension for PyPI as a target in addition to files and GitHub.
This change downloads the sdist (if exists) from PyPI, extracts the contents, and analyzes the extract code in a temp directory.
Closes #540

Add ability to specify a PyPI url as a target

---

docs/getting-started.md

As the title describes, adds a PyPI example as a target for the analysis.

Add PyPI example to Getting Started documentation

---

docs/man/precli.md

The CLI reference or man page for precli contains a list of files that precli will work with. This change adds files that precli will attempt to read for configuration information. Namely, .precli.toml, precli.toml, and pyproject.toml.

Add config files to the CLI reference page

---

docs/man/precli.md

These changes try to make the CLI reference or man page look more closely like a true man page.
* Added section for the exit status to describe expect exit codes
* Added section for copyright

Improve the look of the man page

---

docs/getting-started.md
docs/index.md
docs/requirements.txt
docs/rules.md
mkdocs.yml

The git-revision-date-localized plugin will automatically add the last update date to each markdown page based on the date of the last change in git to the file.

Use mkdocs plugin to put last update time on pages

---

precli/cli/init.py
tests/unit/cli/test_init.py

If precli-init is run without an argument for the -o, it will fail with a traceback due to the argparse.FileType not allowing a default of a str for a file name.
This change does the logic of detecting and opening files manually on its own. It will present an error if the file already exists to prevent overwriting. Except in the case where the file is pyproject.toml and the settings will be appended to it.

Fix traceback when not passing file to -o option

---

precli/cli/init.py
tests/unit/cli/test_init.py
tests/unit/cli/test_main.py

This change modifies precli-init to only write to the output config file (including pyproject.toml) if the configuration settings are not already present.

Prevent precli-init overwriting configuration settings

---

precli/cli/init.py

To avoid modifying existing pyproject settings, precli-init will now only append precli configuration if it doesn't already exist.
Fixes: #697

Only append config to pyproject.toml

---

precli/core/artifact.py

If the file given in the artifact is not local, then the code should not attempt to fetch the last modified date.
This applies to cases where the file is "-" meaning standard input and artifacts with a URL when targeting GitHub repos and such.

Do not try to fetch last modified date if remote file

---

precli/parsers/__init__.py

The base class version of get_file_encoding didn't match the subclasses. This change corrects that.

get_file_encoding inconsistent parameters

---

requirements.txt

In order to support running precli within a browser using PyScript, the tree-sitter libraries which are not pure Python need to match what is available on PyOdide. Current 0.27.0 version of PyOdide has:
tree-sitter==0.23.2
tree-sitter-go==0.23.3
tree-sitter-java==0.23.4
tree-sitter-python==0.23.4
So this change lowsers precli dependency on the python and go libraries to match PyOdide. This should enable PyScript to work, but that requires further testing.

Lower tree-sitter language libraries to work with PyOdide.

---

precli/rules/python/stdlib/ssl_create_unverified_context.py

The ssl_create_unverified_context rule documentation gets extra text as it interprets some of the docstring in the analyze_call function as doc text.
This change will just remove the reference docstring helper text.
Fixes #354

Remove extra text ended up in doc for rule

---

.github/workflows/dependency-review.yml

There was an allowance for using cwe2 as part of the dependency review previously, but now cwe2 is not a dependency so this line isn't needed in dep-review.

Remove cwe2 from dependency review

---

setup.cfg

Not sure if this metadata object changed names over time but some tooling such as LicenseCheck trips up if it's defined as classifier and not classifiers. This also matches current documentation:
https://setuptools.pypa.io/en/latest/userguide/declarative_config.html

Metadata rename classifier to classifiers

---

.github/workflows/unit-test.yml

The unit test workflow runs various tests as defined in tox. This change adds a step for msgfmt that compiles the *.po files to *.mo files.

Add msgfmt step to unit-test build

---

.github/workflows/publish-to-pypi.yml
.github/workflows/publish-to-test-pypi.yml
.github/workflows/upload-asset.yml
setup.py

Upon release to PyPI or Test PyPI, the translation binary files (*.mo) should also be included so that the strings get translated depending on locale.

Publish translation binary files with release

---

.github/workflows/publish-to-pypi.yml
.github/workflows/publish-to-test-pypi.yml
.github/workflows/upload-asset.yml

In order to compile po files to mo, msgfmt command must be installed on the ubuntu build machine.

Ensure msgfmt is installed for publish

---

.github/workflows/unit-test.yml

In order to find issues before the official release of 3.14, start testing with pre-release versions now

Start unit testing with pre-release Python 3.14

---

.github/workflows/publish-to-pypi.yml
.github/workflows/publish-to-test-pypi.yml
.github/workflows/unit-test.yml
.github/workflows/upload-asset.yml

This change switches the version of Python from 3.12 to 3.13 for GitHub action workflows requiring Python that are not unit tests (which tests on all versions).

Use Python 3.13 as defauto verion for testing

---

tests/unit/rules/python/stdlib/imaplib/examples/imaplib_imap4_timeout_global.py

This testcase was setting a timeout on the function rather than relying on the global timeout. That doesn't test the global timeout function much.

Use unset timeout to test global timeout set

---

docs/rules/go/stdlib/crypto-unrestricted-bind.md
precli/rules/go/stdlib/crypto_unrestricted_bind.py
setup.cfg
tests/unit/rules/go/stdlib/crypto/examples/crypto_tls_listen_ipv4.go
tests/unit/rules/go/stdlib/crypto/examples/crypto_tls_listen_ipv6.go
tests/unit/rules/go/stdlib/crypto/test_crypto_unrestricted_bind.py

Checks crypto/tls use of Listen with an address of INADDR_ANY or IN6ADDR_ANY.
Note: currently doesn't properly handle the address argument to the call if given as a variable.
Rule ID is GO005

New rule for Go unrestricted bind

---

docs/rules/go/stdlib/net-unrestricted-bind.md
precli/rules/go/stdlib/net_unrestricted_bind.py
setup.cfg
tests/unit/rules/go/stdlib/crypto/examples/crypto_tls_listen_ipv4.go
tests/unit/rules/go/stdlib/crypto/examples/crypto_tls_listen_ipv6.go
tests/unit/rules/go/stdlib/net/examples/net_listen_ipv4.go
tests/unit/rules/go/stdlib/net/examples/net_listen_ipv6.go
tests/unit/rules/go/stdlib/net/test_net_unrestricted_bind.py

Checks for net package Listen function on whether the address is INADDR_ANY or IN6ADDR_ANY.
Rule ID GO006
Fixes: #759

New GO rule using net Listen as unrestricted address

---

docs/rules.md
docs/rules/go/stdlib/net-http-no-timeout.md
precli/core/cwe.py
precli/rules/go/stdlib/net_http_no_timeout.py
setup.cfg
tests/unit/rules/go/stdlib/net/examples/net_http_listenandserve.go
tests/unit/rules/go/stdlib/net/examples/net_http_listenandservetls.go
tests/unit/rules/go/stdlib/net/examples/net_http_serve.go
tests/unit/rules/go/stdlib/net/examples/net_http_servetls.go
tests/unit/rules/go/stdlib/net/test_net_http_no_timeout.py

Several functions in the net/http package allow starting an http server but do not permit a way to set timeouts. This opens up the server to clients that might abuse it.
Rule ID: GO007

Go rule to check function that do not permit a timeout

---

precli/rules/python/stdlib/hashlib_weak_hash.py
precli/rules/python/stdlib/hmac_weak_hash.py

This change makes it so the insecure hash names are part of the default configuration instead of hard-coded in the rule. As new hashes are considered deprecated, the config can simply be updated.

Make hash names configurable

---

precli/cli/main.py

The language field requires that a tree-sitter-<lang> module has been installed in order for precli to run a query with it. This enables support of languages that aren't natively supported by precli out-of-the-box. The user can install the tree-sitter module and create a rule for a different language.

Verify the language field given in the custom rule

---

custom/eval.rb
custom/python-requests-insecure-verify.yaml
custom/ruby-eval-usage.yaml
precli/core/run.py
precli/parsers/basic.py
precli/parsers/go.py
precli/parsers/java.py
precli/parsers/python.py
precli/targets/__init__.py

This is an example of using the custom rule function with an unsupported language such as Ruby. The prerequiste is the user needs to install tree_sitter_ruby for this to work.
Note: this doesn't work for all tree-sitter parsers available since the tree-sitter in use by precli requires language version 15 to work. So C and Rust currently do not work, possibly others.
Closes: #773

Custom rule example with Ruby language
